on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: check-lint-rot

jobs:
  check-lint-rot:
    uses: easystats/workflows/.github/workflows/check-link-rot.yaml@main
